#-------------------------------
# Site Settings
title: TheXyPod | Horror Game Reviews, News & Upcoming Releases
logo: '/images/logo.svg'
description: Horror game streams, reviews, news, and upcoming releases. Discover the best indie and AAA horror games, trailers, and updates.


#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'Reviews'
      url: '/reviews/'
    - title: 'News'
      url: '/news/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact Me'
      url: '/contact/'


#-------------------------------
# Author Settings
author:
  name: Xy
  avatar: '/images/xy-portrait-icon.webp'


#-------------------------------
# Hero Settings
hero:
  title: TheXyPod
  description: 100% Horror Games
  image: '/images/hero/hero-home-resized.webp'


#-------------------------------
# Contact Settings
contact:
  email: thexypod@gmail.com # Add your email for contact form
  formspree_id: xgvgqwed
  description: Know something I should be afraid of? Whether itâ€™s a horror game worth unearthing, a detail I missed in a review, or a recommendation crawling out of the shadows, send it my way below.

#-------------------------------
# Footer section
social:
- {icon: "fa-brands fa-twitch", name: "Twitch", link: "https://twitch.com/TheXyPod"}
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://youtube.com/@TheXyPod"}
- {icon: "fa-brands fa-discord", name: "Discord", link: "https://discord.gg/AwVkDQRhjx"}
- {icon: "fa-brands fa-steam", name: "Steam", link: "https://steamcommunity.com/id/XyPod/"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com/TheXyPod"}
- {icon: "fa-brands fa-tiktok", name: "TikTok", link: "https://tiktok.com/@TheXyPod"}
- {icon: "fa-brands fa-twitter", name: "Twitter", link: "https://twitter.com/TheXyPod"}



# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-BXZ9NPZ4YR


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
mailchimp-button-text: Join